(() => {
const LOCATIONS=[
{id:'reykjavik',name:'Reykjavík',country:'Iceland',time:'17:48',duration:'1m 43s',horizon:'Low west · coastal',weather:'Maritime cloud reference',travel:'City base · road access',lat:64.147,lon:-21.943,x:45,y:46},
{id:'akureyri',name:'Akureyri',country:'Iceland',time:'17:49',duration:'1m 58s',horizon:'Open valley west',weather:'Inland cloud reference',travel:'Regional airport · drives',lat:65.689,lon:-18.126,x:54,y:35},
{id:'oviedo',name:'Oviedo',country:'Spain',time:'20:29',duration:'1m 46s',horizon:'Western ridge check',weather:'Atlantic cloud reference',travel:'Urban base · rail',lat:43.362,lon:-5.849,x:63,y:73},
{id:'leon',name:'León',country:'Spain',time:'20:30',duration:'1m 50s',horizon:'Open west · late sun',weather:'Interior reference',travel:'Road and rail hub',lat:42.599,lon:-5.567,x:69,y:78},
{id:'palma',name:'Palma',country:'Spain',time:'20:33',duration:'1m 31s',horizon:'Sea horizon west',weather:'Island reference',travel:'Airport base',lat:39.570,lon:2.650,x:83,y:87}
];
const MAPLIBRE_LAYERS={totality:{id:'eclipse-totality-path',type:'line'},sites:{id:'eclipse-reference-sites',type:'circle'},weather:{id:'weather-archive-reference',type:'fill'},horizon:{id:'horizon-reference',type:'line'},travel:{id:'travel-reference',type:'line'}};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={lang:localStorage.getItem('ea-lang')||'en',theme:localStorage.getItem('ea-theme')||'dark',selected:localStorage.getItem('ea-selected')||'leon',layers:JSON.parse(localStorage.getItem('ea-layers')||'{"totality":true,"sites":true,"weather":false,"horizon":false,"travel":false}')};
const t=(key,vars={})=>EclipseTranslations.t(state.lang,key,vars); const save=()=>{localStorage.setItem('ea-lang',state.lang);localStorage.setItem('ea-theme',state.theme);localStorage.setItem('ea-selected',state.selected);localStorage.setItem('ea-layers',JSON.stringify(state.layers));};
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.id);toast.id=setTimeout(()=>el.classList.remove('show'),2600)}
function translate(){document.documentElement.lang=state.lang;$$('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$('#location-search').placeholder=t('search');$('#field-notes').placeholder=t('notesPlaceholder');$('#language').value=state.lang;renderList();renderDetail();renderLayers()}
function renderList(){const q=$('#location-search').value.trim().toLowerCase(),items=LOCATIONS.filter(l=>`${l.name} ${l.country}`.toLowerCase().includes(q));$('#result-count').textContent=t('results',{count:items.length});$('#clear-search').hidden=!q;$('#location-list').innerHTML=items.map(l=>`<li><button class="location-card ${l.id===state.selected?'selected':''}" data-id="${l.id}" type="button"><strong>${l.name}</strong><span>${l.country} · ${t('totalityAt')} ${l.time}</span><small>${l.horizon}</small></button></li>`).join('')||`<li class="empty">${t('none')}</li>`;$$('.location-card').forEach(b=>b.onclick=()=>select(b.dataset.id))}
function renderSites(){$('#map-sites').innerHTML=LOCATIONS.map(l=>`<button class="map-site ${l.id===state.selected?'selected':''}" data-id="${l.id}" style="left:${l.x}%;top:${l.y}%" aria-label="${l.name}"><span>${l.name}</span></button>`).join('');$$('.map-site').forEach(b=>b.onclick=()=>select(b.dataset.id))}
function renderDetail(){const l=LOCATIONS.find(x=>x.id===state.selected)||LOCATIONS[0];$('#location-detail').innerHTML=`<h3>${l.name}, ${l.country}</h3><p class="time-line">${t('totalityAt')} <strong>${l.time}</strong> · ${t('duration')} <strong>${l.duration}</strong></p><dl><div><dt>${t('horizon')}</dt><dd>${l.horizon}</dd></div><div><dt>${t('weather')}</dt><dd>${l.weather}</dd></div><div><dt>${t('travel')}</dt><dd>${l.travel}</dd></div><div><dt>${t('coordinates')}</dt><dd>${l.lat.toFixed(3)}°, ${l.lon.toFixed(3)}°</dd></div></dl>`;$$('.map-site').forEach(s=>s.classList.toggle('selected',s.dataset.id===l.id))}
function select(id){state.selected=id;save();renderList();renderDetail();toast(t('selectedToast',{name:LOCATIONS.find(l=>l.id===id).name}))}
function renderLayers(){$$('.layer-toggle').forEach(b=>{const on=!!state.layers[b.dataset.layer];b.classList.toggle('active',on);b.setAttribute('aria-pressed',on)});$('#totality-line').classList.toggle('hidden',!state.layers.totality);$('#map-sites').classList.toggle('hidden',!state.layers.sites);$('#weather-overlay').classList.toggle('visible',state.layers.weather);$('#horizon-overlay').classList.toggle('visible',state.layers.horizon);$('#travel-overlay').classList.toggle('visible',state.layers.travel)}
function download(name,data,type){const blob=new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url)}
function exportCalendar(){const l=LOCATIONS.find(x=>x.id===state.selected);download(`eclipse-atlas-${l.id}.ics`,`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Eclipse Atlas//EN\r\nBEGIN:VEVENT\r\nUID:eclipse-atlas-20260812-${l.id}\r\nDTSTAMP:20260812T000000Z\r\nDTSTART:20260812T170000Z\r\nDTEND:20260812T210000Z\r\nSUMMARY:2026 Total Solar Eclipse — ${l.name}\r\nLOCATION:${l.name}, ${l.country}\r\nDESCRIPTION:Archive reference. Totality at ${l.time}; duration ${l.duration}.\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`,'text/calendar');toast(t('calendarDone'))}
function nearest(){if(!navigator.geolocation)return toast(t('geoUnavailable'));toast(t('locating'));navigator.geolocation.getCurrentPosition(p=>{let best=LOCATIONS[0],dist=Infinity;LOCATIONS.forEach(l=>{const d=Math.hypot(l.lat-p.coords.latitude,l.lon-p.coords.longitude);if(d<dist){dist=d;best=l}});select(best.id);toast(t('nearest',{name:best.name}))},()=>toast(t('geoDenied')),{timeout:8000})}
function init(){document.documentElement.dataset.theme=state.theme;$('#field-notes').value=localStorage.getItem('ea-notes')||'';$('#reminder-interest').checked=localStorage.getItem('ea-reminder')==='true';renderSites();translate();$('#language').onchange=e=>{state.lang=e.target.value;save();translate()};$('#theme-toggle').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;save();toast(t('themeSaved'))};$('#location-search').oninput=renderList;$('#clear-search').onclick=()=>{$('#location-search').value='';renderList()};$('#geolocate').onclick=nearest;$('#calendar-button').onclick=exportCalendar;$$('.layer-toggle').forEach(b=>b.onclick=()=>{state.layers[b.dataset.layer]=!state.layers[b.dataset.layer];save();renderLayers();toast(t(state.layers[b.dataset.layer]?'layerOn':'layerOff',{name:b.textContent}))});$('#reset-layers').onclick=()=>{state.layers={totality:true,sites:true,weather:false,horizon:false,travel:false};save();renderLayers();toast(t('layersReset'))};$('#save-location').onclick=()=>{localStorage.setItem('ea-saved',state.selected);toast(t('saved'))};$('#copy-location').onclick=async()=>{const l=LOCATIONS.find(x=>x.id===state.selected),text=`${l.name}, ${l.country} — totality ${l.time}, ${l.duration}; ${l.horizon}`;try{await navigator.clipboard.writeText(text);toast(t('copied'))}catch{toast(text)}};$('#field-notes').oninput=e=>{localStorage.setItem('ea-notes',e.target.value);$('#notes-status').textContent=t('localOnly')};$('#download-notes').onclick=()=>download('eclipse-atlas-notes.txt',`Eclipse Atlas — 2026 Archive\n\n${$('#field-notes').value}`,'text/plain');$('#reminder-form').onsubmit=e=>{e.preventDefault();localStorage.setItem('ea-reminder',$('#reminder-interest').checked);toast(t('preferenceSaved'))};const dialog=$('#info-dialog'),open=()=>dialog.showModal();$('#archive-info').onclick=open;$('#privacy-button').onclick=open;$('.dialog-close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()}}
document.addEventListener('DOMContentLoaded',init);window.EclipseAtlas={MAPLIBRE_LAYERS};})();