(() => {
  const FEATURED = [
    { id:'reykjavik', name:'Reykjavík', country:'Iceland', time:'17:48', duration:'1m 43s', horizon:'Low west · coastal', weather:'Maritime cloud reference', travel:'City base · road access', lat:64.147, lon:-21.943, featured:true },
    { id:'akureyri', name:'Akureyri', country:'Iceland', time:'17:49', duration:'1m 58s', horizon:'Open valley west', weather:'Inland cloud reference', travel:'Regional airport · drives', lat:65.689, lon:-18.126, featured:true },
    { id:'oviedo', name:'Oviedo', country:'Spain', time:'20:29', duration:'1m 46s', horizon:'Western ridge check', weather:'Atlantic cloud reference', travel:'Urban base · rail', lat:43.362, lon:-5.849, featured:true },
    { id:'leon', name:'León', country:'Spain', time:'20:30', duration:'1m 50s', horizon:'Open west · late sun', weather:'Interior reference', travel:'Road and rail hub', lat:42.599, lon:-5.567, featured:true },
    { id:'palma', name:'Palma', country:'Spain', time:'20:33', duration:'1m 31s', horizon:'Sea horizon west', weather:'Island reference', travel:'Airport base', lat:39.570, lon:2.650, featured:true }
  ];
  const LAYER_DEFINITIONS = { totality:{id:'eclipse-totality-path',kind:'line'}, sites:{id:'eclipse-featured-sites',kind:'marker'}, weather:{id:'weather-archive-reference',kind:'overlay'}, horizon:{id:'horizon-reference',kind:'overlay'} };
  const $ = (s,r=document) => r.querySelector(s); const $$ = (s,r=document) => [...r.querySelectorAll(s)];
  const state = { lang:localStorage.getItem('ea-lang') || 'en', theme:localStorage.getItem('ea-theme') || 'dark', selectedId:localStorage.getItem('ea-selected') || 'leon', selectedPlace:null, layers:JSON.parse(localStorage.getItem('ea-layers') || '{"totality":true,"sites":true,"weather":false,"horizon":false}') };
  const t = (key,vars={}) => EclipseTranslations.t(state.lang,key,vars);
  let map, featuredLayer, selectedMarker, totalityLayer, weatherLayer, horizonLayer;
  const persist = () => { localStorage.setItem('ea-lang',state.lang); localStorage.setItem('ea-theme',state.theme); localStorage.setItem('ea-selected',state.selectedId); localStorage.setItem('ea-layers',JSON.stringify(state.layers)); };
  function toast(message){ const el=$('#toast'); el.textContent=message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer=setTimeout(()=>el.classList.remove('show'),2600); }
  function selected(){ return state.selectedPlace || FEATURED.find(l=>l.id===state.selectedId) || FEATURED[0]; }
  function initMap(){
    if(!window.L){ $('#world-map').innerHTML=`<p class="map-error">${t('mapUnavailable')}</p>`; return; }
    map=L.map('world-map',{zoomControl:true,worldCopyJump:true}).setView([35,-18],3);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);
    featuredLayer=L.layerGroup().addTo(map); totalityLayer=L.layerGroup().addTo(map); weatherLayer=L.layerGroup(); horizonLayer=L.layerGroup();
    const path=[[75,50],[69,-20],[65,-22],[58,-17],[48,-10],[43,-6],[40,0],[39,3]];
    L.polyline(path,{color:'#ffb85c',weight:5,opacity:.85,dashArray:'10 8'}).addTo(totalityLayer);
    L.polygon([[62,-30],[68,-22],[66,-12],[59,-14]],{color:'#8fe3db',weight:1,fillColor:'#8fe3db',fillOpacity:.14}).bindTooltip(t('weatherOverlay')).addTo(weatherLayer);
    L.polyline([[43,-9],[42,-6],[41,-4],[40,-1]],{color:'#ffe0a3',weight:4,opacity:.75}).bindTooltip(t('horizonOverlay')).addTo(horizonLayer);
    FEATURED.forEach(location=>{ const marker=L.circleMarker([location.lat,location.lon],{radius:7,color:'#07111f',weight:2,fillColor:'#8fe3db',fillOpacity:1}); marker.bindTooltip(location.name); marker.on('click',()=>chooseFeatured(location.id,true)); marker.addTo(featuredLayer); });
    renderLayers();
  }
  function chooseFeatured(id,fly=false){ state.selectedPlace=null; state.selectedId=id; persist(); renderFeatured(); renderDetail(); if(fly&&map){const l=selected(); map.flyTo([l.lat,l.lon],7,{duration:.7});} updateSelectedMarker(); toast(t('selectedToast',{name:selected().name})); }
  function choosePlace(place,fly=true){ state.selectedPlace=place; state.selectedId=''; persist(); renderFeatured(); renderDetail(); if(fly&&map) map.flyTo([place.lat,place.lon],Math.max(7,Math.min(12,place.zoom||10)),{duration:.7}); updateSelectedMarker(); toast(t('selectedToast',{name:place.name})); }
  function updateSelectedMarker(){ if(!map) return; if(selectedMarker) selectedMarker.remove(); const l=selected(); selectedMarker=L.marker([l.lat,l.lon],{title:l.name}).addTo(map); selectedMarker.bindPopup(`<strong>${escapeHtml(l.name)}</strong>`); }
  function renderFeatured(){ $('#location-list').innerHTML=FEATURED.map(l=>`<li><button class="location-card ${!state.selectedPlace&&l.id===state.selectedId?'selected':''}" data-id="${l.id}" type="button"><strong>${l.name}</strong><span>${l.country} · ${t('totalityAt')} ${l.time}</span><small>${l.horizon}</small></button></li>`).join(''); $$('.location-card').forEach(b=>b.onclick=()=>chooseFeatured(b.dataset.id,true)); }
  function renderDetail(){ const l=selected(); const featured=l.featured; $('#location-detail').innerHTML=featured ? `<h3>${escapeHtml(l.name)}, ${escapeHtml(l.country)}</h3><p class="time-line">${t('totalityAt')} <strong>${l.time}</strong> · ${t('duration')} <strong>${l.duration}</strong></p><dl><div><dt>${t('horizon')}</dt><dd>${l.horizon}</dd></div><div><dt>${t('weather')}</dt><dd>${l.weather}</dd></div><div><dt>${t('travel')}</dt><dd>${l.travel}</dd></div><div><dt>${t('coordinates')}</dt><dd>${l.lat.toFixed(3)}°, ${l.lon.toFixed(3)}°</dd></div></dl>` : `<h3>${escapeHtml(l.name)}</h3><p class="time-line">${t('worldwideSelection')}</p><dl><div><dt>${t('coordinates')}</dt><dd>${l.lat.toFixed(4)}°, ${l.lon.toFixed(4)}°</dd></div><div><dt>${t('eclipseStatus')}</dt><dd>${t('lookupRequired')}</dd></div></dl><p class="detail-note">${t('lookupNote')}</p>`; }
  function renderLayers(){ if(!map) return; const list=[[totalityLayer,'totality'],[featuredLayer,'sites'],[weatherLayer,'weather'],[horizonLayer,'horizon']]; list.forEach(([layer,key])=>{const on=!!state.layers[key]; if(on&&!map.hasLayer(layer)) layer.addTo(map); if(!on&&map.hasLayer(layer)) map.removeLayer(layer);}); $$('.layer-toggle').forEach(b=>{const on=!!state.layers[b.dataset.layer];b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));}); }
  function translate(){ document.documentElement.lang=state.lang; $$('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n)); $('#language').value=state.lang; $('#world-search-input').placeholder=t('worldSearchPlaceholder'); $('#field-notes').placeholder=t('notesPlaceholder'); renderFeatured(); renderDetail(); if(map){ weatherLayer.eachLayer(layer=>layer.setTooltipContent && layer.setTooltipContent(t('weatherOverlay'))); horizonLayer.eachLayer(layer=>layer.setTooltipContent && layer.setTooltipContent(t('horizonOverlay'))); } }
  async function searchPlaces(query){
    const status=$('#world-search-status'), results=$('#world-search-results'); results.innerHTML=''; status.textContent=t('searching');
    try{ const response=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&addressdetails=1&q=${encodeURIComponent(query)}`,{headers:{Accept:'application/json'}}); if(!response.ok) throw new Error('search failed'); const places=await response.json(); if(!places.length){status.textContent=t('noPlaces');return;} status.textContent=t('placeResults',{count:places.length}); results.innerHTML=places.map((p,i)=>`<li><button class="place-result" type="button" data-index="${i}"><strong>${escapeHtml(shortName(p.display_name))}</strong><span>${escapeHtml(p.display_name)}</span></button></li>`).join(''); $$('.place-result').forEach(button=>button.onclick=()=>{const p=places[Number(button.dataset.index)];choosePlace({id:`place-${p.place_id}`,name:shortName(p.display_name),country:p.address?.country||'',lat:Number(p.lat),lon:Number(p.lon),zoom:10,featured:false});results.innerHTML='';status.textContent=t('placeSelected');}); }
    catch(error){ status.textContent=t('searchError'); }
  }
  function shortName(displayName){return displayName.split(',').slice(0,2).join(',');}
  function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
  function exportCalendar(){const l=selected();const safe=(l.name||'location').replace(/[^a-z0-9]+/gi,'-').toLowerCase();const description=l.featured?`Archive reference. Totality at ${l.time}; duration ${l.duration}.`:'Worldwide archive location. Eclipse circumstances require a verified reference lookup.';download(`eclipse-atlas-${safe}.ics`,`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Eclipse Atlas//EN\r\nBEGIN:VEVENT\r\nUID:eclipse-atlas-20260812-${safe}\r\nDTSTAMP:20260812T000000Z\r\nDTSTART:20260812T170000Z\r\nDTEND:20260812T210000Z\r\nSUMMARY:2026 Total Solar Eclipse — ${l.name}\r\nLOCATION:${l.name}\r\nDESCRIPTION:${description}\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`,'text/calendar');toast(t('calendarDone'));}
  function download(name,data,type){const blob=new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url);}
  function nearestFeatured(){ if(!navigator.geolocation){toast(t('geoUnavailable'));return;} toast(t('locating'));navigator.geolocation.getCurrentPosition(p=>{let best=FEATURED[0],distance=Infinity;FEATURED.forEach(l=>{const d=Math.hypot(l.lat-p.coords.latitude,l.lon-p.coords.longitude);if(d<distance){distance=d;best=l;}});chooseFeatured(best.id,true);toast(t('nearest',{name:best.name}));},()=>toast(t('geoDenied')),{timeout:8000}); }
  function init(){ document.documentElement.dataset.theme=state.theme; $('#field-notes').value=localStorage.getItem('ea-notes')||''; $('#reminder-interest').checked=localStorage.getItem('ea-reminder')==='true'; initMap(); renderFeatured(); renderDetail(); updateSelectedMarker(); translate();
    $('#language').onchange=e=>{state.lang=e.target.value;persist();translate();}; $('#theme-toggle').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;persist();toast(t('themeSaved'));};
    $('#world-search-form').onsubmit=e=>{e.preventDefault();const query=$('#world-search-input').value.trim();if(query.length<2){$('#world-search-status').textContent=t('searchTooShort');return;}searchPlaces(query);}; $('#use-my-location').onclick=nearestFeatured;
    $$('.layer-toggle').forEach(b=>b.onclick=()=>{const key=b.dataset.layer;state.layers[key]=!state.layers[key];persist();renderLayers();toast(t(state.layers[key]?'layerOn':'layerOff',{name:b.textContent}));}); $('#reset-map').onclick=()=>{state.layers={totality:true,sites:true,weather:false,horizon:false};persist();renderLayers();if(map)map.flyTo([35,-18],3,{duration:.7});toast(t('mapReset'));};
    $('#save-location').onclick=()=>{localStorage.setItem('ea-saved-location',JSON.stringify(selected()));toast(t('saved'));}; $('#copy-location').onclick=async()=>{const l=selected(),text=`${l.name} — ${l.lat.toFixed(4)}, ${l.lon.toFixed(4)}`;try{await navigator.clipboard.writeText(text);toast(t('copied'));}catch{toast(text);}};
    $('#calendar-button').onclick=exportCalendar; $('#field-notes').oninput=e=>{localStorage.setItem('ea-notes',e.target.value);$('#notes-status').textContent=t('localOnly');}; $('#download-notes').onclick=()=>download('eclipse-atlas-notes.txt',`Eclipse Atlas — 2026 Archive\n\n${$('#field-notes').value}`,'text/plain'); $('#reminder-form').onsubmit=e=>{e.preventDefault();localStorage.setItem('ea-reminder',$('#reminder-interest').checked);toast(t('preferenceSaved'));};
    const dialog=$('#info-dialog'),open=()=>dialog.showModal();$('#archive-info').onclick=open;$('#privacy-button').onclick=open;$('.dialog-close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close();};
  }
  document.addEventListener('DOMContentLoaded',init); window.EclipseAtlas={LAYER_DEFINITIONS};
})();